// See https://developer.mozilla.org/docs/Web/CSS/CSS_colors/Applying_color
export const cssColorProperties: string[] = [
    'background-color',
    'background',
    'border',
    'border-block-start-color',
    'border-block-end-color',
    'border-inline-start-color',
    'border-inline-end-color',
    'border-bottom-color',
    'border-color',
    'border-left-color',
    'border-right-color',
    'border-top-color',
    'box-shadow',
    'caret-color',
    'color',
    'column-rule',
    'column-rule-color',
    'filter',
    'opacity',
    'outline-color',
    'outline',
    'text-decoration',
    'text-decoration-color',
    'text-shadow',
];
